# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: pantegnos

env:
  - CGO_ENABLED=0

builds:
  - id: pantegnos-cli
    main: ./cmd/pantegnos
    binary: pantegnos
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: pantegnos-cli
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
