name: Pantegnos Manual Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Create Unified Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Auto Increment Semver
        uses: MCKanpolat/auto-semver-action@v2
        id: versioning
        with:
          releaseType: patch
          incrementPerCommit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        run: |
          git tag "v${{ steps.versioning.outputs.version }}"
          git push origin "v${{ steps.versioning.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
